roles:
- src: geerlingguy.java
  name: geerlingguy.java

- src: geerlingguy.jenkins
  name: geerlingguy.jenkins

- src: geerlingguy.pip
  name: geerlingguy.pip

- src: geerlingguy.docker
  name: geerlingguy.docker

- src: geerlingguy.git
  name: geerlingguy.git

- src: geerlingguy.mysql
  name: geerlingguy.mysql

- src: geerlingguy.gogs
  name: geerlingguy.gogs
