- name: Playbook to install jenkins 
  hosts: "{{ dev }}"
  vars_files:
  - ../vars/vars.yaml
  become: true
  vars:
    #jenkins_hostname: jenkins.example.com
    java_packages:
      - openjdk-8-jdk
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins