- name: Playbook to install jenkins 
  hosts: "{{ dev }}"
  vars_files:
  - ../vars/vars.yaml
  become: true
  tasks:
    - name: debug user name
      debug:
        msg: ansible user is {{ ansible_ssh_user }}
    - import_role:
        name: geerlingguy.java

  # roles:
  #   #- role: geerlingguy.pip
  #   - role: geerlingguy.docker