- name: playbook to test delegate_to task
  hosts: "{{ target-hosts }}"
  vars_files:
  - vars/vars.yaml
  tasks:
  - name: download list of all repos to localhost
    uri:
        url: https://api.github.com/users/enggalilioo/repos
        dest: ~/dev/ansibletest/repo.json
    delegate_to: localhost