- name: Playbook to install jenkins 
  hosts: dev2
  become: true
  vars:
    #jenkins_hostname: jenkins.example.com
    java_packages:
      - openjdk-8-jdk

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins