- name: playbook for using jinja
  hosts: "{{ target-hosts }}"
  vars_files:
  - vars/vars.yaml
  become: yes
  tasks:
  - name: with_list -> loop
    template:
        dest: /tmp/hosts
        src: templates/hosts.j2